import { StyleSheet } from 'react-native';
import { COLORS } from './color';

export const fieldStyles = StyleSheet.create({
  container: {
    gap: 6,
    marginBottom: 16,
  },
  label: {
    fontSize: 12,
    color: COLORS.label,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: COLORS.input_background,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 15,
    color: COLORS.body,
  },
  inputError: {
    borderColor: '#E57373',
  },
  multiline: {
    height: 80,
    textAlignVertical: 'top' as const,
  },
  error: {
    fontSize: 12,
    color: '#E57373',
  },
});

export const checkoutStyles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: COLORS.off_white,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    backgroundColor: COLORS.off_white,
  },
  backBtn: {
    width: 36,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 16,
    letterSpacing: 4,
    color: COLORS.title_active,
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 8,
  },
  section: {
    backgroundColor: COLORS.off_white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  sectionTitle: {
    fontSize: 13,
    letterSpacing: 2,
    color: COLORS.title_active,
    fontWeight: '700',
    marginBottom: 16,
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  orderItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  orderItemQty: {
    fontSize: 13,
    color: COLORS.secondary,
    fontWeight: '600',
    minWidth: 24,
  },
  orderItemName: {
    fontSize: 13,
    color: COLORS.body,
    flex: 1,
  },
  orderItemPrice: {
    fontSize: 13,
    color: COLORS.body,
    fontWeight: '500',
  },
  orderDivider: {
    height: 1,
    backgroundColor: COLORS.line,
    marginVertical: 10,
  },
  orderTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderTotalLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.body,
    letterSpacing: 1,
  },
  orderTotalValue: {
    fontSize: 18,
    color: COLORS.secondary,
    fontWeight: '700',
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.line,
    marginBottom: 10,
    backgroundColor: COLORS.input_background,
  },
  paymentOptionSelected: {
    borderColor: COLORS.secondary,
    backgroundColor: '#2A1810',
  },
  paymentLabel: {
    flex: 1,
    fontSize: 14,
    color: COLORS.body,
  },
  paymentLabelSelected: {
    color: COLORS.secondary,
    fontWeight: '500',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.off_white,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  footerTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerTotalLabel: {
    fontSize: 14,
    color: COLORS.label,
    letterSpacing: 1,
  },
  footerTotalValue: {
    fontSize: 20,
    color: COLORS.secondary,
    fontWeight: '700',
  },
  placeOrderBtn: {
    backgroundColor: COLORS.title_active,
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  placeOrderBtnDisabled: {
    opacity: 0.5,
  },
  placeOrderBtnText: {
    color: COLORS.off_white,
    fontSize: 15,
    letterSpacing: 3,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: COLORS.off_white,
    borderRadius: 16,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    gap: 12,
  },
  successIcon: {
    marginBottom: 8,
  },
  successTitle: {
    fontSize: 24,
    letterSpacing: 3,
    color: COLORS.title_active,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  orderId: {
    fontSize: 14,
    color: COLORS.secondary,
    letterSpacing: 1,
    marginBottom: 4,
  },
  successDetails: {
    width: '100%',
    backgroundColor: COLORS.input_background,
    borderRadius: 8,
    padding: 14,
    gap: 4,
  },
  successDetailTitle: {
    fontSize: 11,
    color: COLORS.label,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  successDetailText: {
    fontSize: 14,
    color: COLORS.body,
    lineHeight: 22,
  },
  successSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  successSummaryLabel: {
    fontSize: 13,
    color: COLORS.label,
  },
  successSummaryValue: {
    fontSize: 14,
    color: COLORS.body,
    fontWeight: '600',
  },
  successNote: {
    fontSize: 12,
    color: COLORS.placeholder,
    textAlign: 'center',
    lineHeight: 18,
  },
  successBtn: {
    backgroundColor: COLORS.title_active,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 8,
    marginTop: 8,
    width: '100%',
    alignItems: 'center',
  },
  successBtnText: {
    color: COLORS.off_white,
    fontSize: 14,
    letterSpacing: 2,
    fontWeight: '600',
  },
});
