import { StyleSheet } from 'react-native';
import { THEME } from './theme';

export const fieldStyles = StyleSheet.create({
  container: {
    gap: 6,
    marginBottom: 16,
  },
  label: {
    fontSize: THEME.fontSize.xs,
    color: THEME.colors.textSecondary,
    letterSpacing: 1,
    textTransform: 'uppercase',
    fontWeight: THEME.fontWeight.medium,
  },
  input: {
    backgroundColor: THEME.colors.backgroundAlt,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    borderRadius: THEME.radius.sm,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: THEME.fontSize.base,
    color: THEME.colors.textPrimary,
  },
  inputError: {
    borderColor: THEME.colors.salePrice,
  },
  multiline: {
    height: 80,
    textAlignVertical: 'top' as const,
  },
  error: {
    fontSize: THEME.fontSize.xs,
    color: THEME.colors.salePrice,
  },
});

export const checkoutStyles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: THEME.colors.backgroundAlt,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
    backgroundColor: THEME.colors.background,
  },
  backBtn: {
    width: 36,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: THEME.fontSize.lg,
    letterSpacing: 3,
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.semibold,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 8,
  },
  section: {
    backgroundColor: THEME.colors.background,
    borderRadius: THEME.radius.md,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: THEME.colors.border,
  },
  sectionTitle: {
    fontSize: THEME.fontSize.xs,
    letterSpacing: 2,
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.bold,
    marginBottom: 16,
  },
  orderItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  orderItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  orderItemQty: {
    fontSize: THEME.fontSize.sm,
    color: THEME.colors.salePrice,
    fontWeight: THEME.fontWeight.semibold,
    minWidth: 24,
  },
  orderItemName: {
    fontSize: THEME.fontSize.sm,
    color: THEME.colors.textSecondary,
    flex: 1,
  },
  orderItemPrice: {
    fontSize: THEME.fontSize.sm,
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.medium,
  },
  orderDivider: {
    height: 1,
    backgroundColor: THEME.colors.border,
    marginVertical: 10,
  },
  orderTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderTotalLabel: {
    fontSize: THEME.fontSize.base,
    fontWeight: THEME.fontWeight.bold,
    color: THEME.colors.textPrimary,
  },
  orderTotalValue: {
    fontSize: THEME.fontSize.xl,
    color: THEME.colors.salePrice,
    fontWeight: THEME.fontWeight.bold,
  },
  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: THEME.radius.sm,
    borderWidth: 1,
    borderColor: THEME.colors.border,
    marginBottom: 10,
    backgroundColor: THEME.colors.backgroundAlt,
  },
  paymentOptionSelected: {
    borderColor: THEME.colors.primary,
    backgroundColor: THEME.colors.background,
  },
  paymentLabel: {
    flex: 1,
    fontSize: THEME.fontSize.base,
    color: THEME.colors.textSecondary,
  },
  paymentLabelSelected: {
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.medium,
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: THEME.colors.background,
    borderTopWidth: 1,
    borderTopColor: THEME.colors.border,
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  footerTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerTotalLabel: {
    fontSize: THEME.fontSize.base,
    color: THEME.colors.textSecondary,
  },
  footerTotalValue: {
    fontSize: THEME.fontSize.xxl,
    color: THEME.colors.salePrice,
    fontWeight: THEME.fontWeight.bold,
  },
  placeOrderBtn: {
    backgroundColor: THEME.colors.primary,
    paddingVertical: 16,
    borderRadius: THEME.radius.sm,
    alignItems: 'center',
  },
  placeOrderBtnDisabled: {
    opacity: 0.5,
  },
  placeOrderBtnText: {
    color: THEME.colors.white,
    fontSize: THEME.fontSize.base,
    letterSpacing: 2,
    fontWeight: THEME.fontWeight.semibold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: THEME.colors.background,
    borderRadius: THEME.radius.lg,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    gap: 12,
  },
  successIcon: {
    marginBottom: 4,
  },
  successTitle: {
    fontSize: THEME.fontSize.xxl,
    letterSpacing: 2,
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.bold,
  },
  orderId: {
    fontSize: THEME.fontSize.sm,
    color: THEME.colors.salePrice,
    letterSpacing: 1,
    marginBottom: 4,
  },
  successDetails: {
    width: '100%',
    backgroundColor: THEME.colors.backgroundAlt,
    borderRadius: THEME.radius.sm,
    padding: 14,
    gap: 4,
  },
  successDetailTitle: {
    fontSize: THEME.fontSize.xs,
    color: THEME.colors.textMuted,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  successDetailText: {
    fontSize: THEME.fontSize.base,
    color: THEME.colors.textPrimary,
    lineHeight: 22,
  },
  successSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.border,
  },
  successSummaryLabel: {
    fontSize: THEME.fontSize.sm,
    color: THEME.colors.textSecondary,
  },
  successSummaryValue: {
    fontSize: THEME.fontSize.base,
    color: THEME.colors.textPrimary,
    fontWeight: THEME.fontWeight.semibold,
  },
  successNote: {
    fontSize: THEME.fontSize.xs,
    color: THEME.colors.textMuted,
    textAlign: 'center',
    lineHeight: 18,
  },
  successBtn: {
    backgroundColor: THEME.colors.primary,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: THEME.radius.sm,
    marginTop: 8,
    width: '100%',
    alignItems: 'center',
  },
  successBtnText: {
    color: THEME.colors.white,
    fontSize: THEME.fontSize.base,
    letterSpacing: 1.5,
    fontWeight: THEME.fontWeight.semibold,
  },
});
