export const THEME = {
  colors: {
    background: '#FFFFFF',
    backgroundAlt: '#F8F9FA',
    primary: '#11142A',
    textPrimary: '#1F1F1F',
    textSecondary: '#7A7A7A',
    textMuted: '#AAAAAA',
    salePrice: '#E8334A',
    star: '#F4A623',
    border: '#EFEFEF',
    divider: '#F0F0F0',
    cardBg: '#F8F9FA',
    badge: '#E8334A',
    white: '#FFFFFF',
    heartActive: '#E8334A',
    heroBg: '#D0E8F0',
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 100,
  },
  fontSize: {
    xs: 10,
    sm: 12,
    base: 14,
    lg: 16,
    xl: 18,
    xxl: 22,
    xxxl: 36,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    extrabold: '800' as const,
  },
} as const;
