import { StyleSheet } from 'react-native';
import { COLORS } from './color';

export const cartStyles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: COLORS.off_white,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    letterSpacing: 2,
    color: COLORS.title_active,
    textTransform: 'uppercase',
  },
  emptySubtitle: {
    fontSize: 14,
    color: COLORS.label,
    textAlign: 'center',
    lineHeight: 22,
  },
  shopBtn: {
    backgroundColor: COLORS.title_active,
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 8,
    marginTop: 8,
  },
  shopBtnText: {
    color: COLORS.off_white,
    fontSize: 14,
    letterSpacing: 2,
    fontWeight: '600',
  },
  list: {
    padding: 16,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  itemCount: {
    fontSize: 13,
    color: COLORS.label,
    letterSpacing: 0.5,
  },
  clearText: {
    fontSize: 13,
    color: COLORS.secondary,
  },
  separator: {
    height: 1,
    backgroundColor: COLORS.line,
    marginVertical: 16,
  },
  cartItem: {
    flexDirection: 'row',
    gap: 12,
  },
  itemImage: {
    width: 100,
    height: 120,
    borderRadius: 8,
    backgroundColor: COLORS.input_background,
  },
  itemInfo: {
    flex: 1,
    gap: 6,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemCategory: {
    fontSize: 12,
    color: COLORS.body,
    letterSpacing: 2,
    fontWeight: '600',
  },
  itemTitle: {
    fontSize: 13,
    color: COLORS.label,
    lineHeight: 19,
  },
  itemVariant: {
    fontSize: 12,
    color: COLORS.placeholder,
  },
  itemFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  qtyBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.input_background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.line,
  },
  qtyText: {
    fontSize: 15,
    color: COLORS.body,
    width: 28,
    textAlign: 'center',
    fontWeight: '500',
  },
  itemPrice: {
    fontSize: 16,
    color: COLORS.secondary,
    fontWeight: '500',
  },
  summary: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.off_white,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 14,
    letterSpacing: 2,
    color: COLORS.body,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  summaryValue: {
    fontSize: 18,
    color: COLORS.secondary,
    fontWeight: '600',
    letterSpacing: 1,
  },
  shippingNote: {
    fontSize: 12,
    color: COLORS.placeholder,
    lineHeight: 18,
  },
  checkoutBtn: {
    backgroundColor: COLORS.title_active,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 16,
    borderRadius: 8,
  },
  checkoutBtnText: {
    color: COLORS.off_white,
    fontSize: 14,
    letterSpacing: 2,
    fontWeight: '600',
  },
  continueBtn: {
    alignItems: 'center',
    paddingVertical: 4,
  },
  continueBtnText: {
    fontSize: 13,
    color: COLORS.label,
    letterSpacing: 0.5,
  },
});
